services:
  postgres:
    ports:
      - "8333:5432"
    image: postgres:14.6
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local


