spring:
    application:
        name=TransactionLedger
    datasource:
        driverClassName=org.postgresql.Driver
        url: jdbc:postgresql://localhost:8333/ledger
        username: local
        password: local

